# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=26.2
loader_version=0.18.4
ae2_version=15.0.3-alpha

# Mod Properties
mod_version=1.5.2-26.2-Fabric
forge_mod_version=1.5.2-26.2-Forge
neoforge_mod_version=1.5.2-26.2-Neoforge
maven_group=com.skniro
archives_base_name=UsefulFood_Reborn
mod_author=skniro
# Dependencies
# check this on https://modmuss50.me/fabric.html
#Fabric api
fabric_version=0.152.1+26.2
forge_version=65.1.0
forge_version_range=[51,)

rei_version=21.11.814
jei_version=15.2.0.22

# Neoforge Properties
minecraft_version_range=[26.2,26.3)
mod_id=usefulfood
mod_name=UsefulFood_Reborn
mod_license=MIT License
mod_group_id=com.skniro.usefulfood
mod_description=
mod_authors=skniro

# Neoforge
neo_version=26.2.0.49-beta
neo_version_range=[26.1.2.20,)
loader_version_range=[2,)






