package com.skniro.usefulfood.datagen;

import com.google.common.collect.Lists;
import com.skniro.usefulfood.block.UsefulFoodCakeBlocks;
import com.skniro.usefulfood.block.UsefulFoodJamBlocks;
import com.skniro.usefulfood.item.UsefulFoodItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.fabricmc.fabric.api.tag.convention.v2.ConventionalItemTags;
import net.minecraft.block.Blocks;
import net.minecraft.data.server.recipe.*;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.Items;
import net.minecraft.recipe.Ingredient;
import net.minecraft.recipe.book.RecipeCategory;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.ItemTags;
import net.minecraft.util.Util;

import java.util.List;
import java.util.concurrent.CompletableFuture;

public class UsefulFoodRecipeGenerator extends FabricRecipeProvider {
    public UsefulFoodRecipeGenerator(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    public void generate(RecipeExporter exporter) {
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MilkBottle,1).input(Items.GLASS_BOTTLE,1).input(Items.MILK_BUCKET).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.MILK_BUCKET)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.ChocolateMilkBottle).input(Items.COCOA_BEANS).input(Items.GLASS_BOTTLE).input(UsefulFoodItems.MilkBottle).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Cheese).input(UsefulFoodItems.HotMilkBottle).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.HotMilkBottle)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.SugarCube).input(Items.SUGAR,2).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.caramelapple).input(Items.APPLE).input(Items.STICK).input(UsefulFoodItems.caramel).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.caramel)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.PumpkinSoup).input(Items.BOWL).input(Items.PUMPKIN).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Salad).input(Items.POPPY).input(Items.DANDELION).input(Items.WHEAT_SEEDS).input(Items.BOWL).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Marshmallow).input(Items.SUGAR,3).input(Items.BOWL).input(Items.WATER_BUCKET).input(Items.STICK).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.VanillaIceCream).input(Items.SNOWBALL).input(Items.SUGAR).input(Items.BOWL).input(UsefulFoodItems.MilkBottle).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.BreadSlice,5).input(Items.BREAD).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BREAD)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.PorkWich).input(UsefulFoodItems.BreadSlice,2).input(Items.COOKED_PORKCHOP).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Steakwich).input(UsefulFoodItems.BreadSlice,2).input(Items.COOKED_BEEF).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chickenwich).input(UsefulFoodItems.BreadSlice,2).input(Items.COOKED_CHICKEN).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Eggwich).input(UsefulFoodItems.BreadSlice,2).input(UsefulFoodItems.FriedEgg).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Biscuit).input(Items.WHEAT,2).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.WHEAT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MuttonSandwich).input(Items.COOKED_MUTTON).input(UsefulFoodItems.BreadSlice,2).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.SquidSandwich).input(UsefulFoodItems.SquidTentacleCooked).input(UsefulFoodItems.BreadSlice,2).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MagicAppleJuice).input(Items.GOLDEN_APPLE,2).input(Items.ENCHANTED_GOLDEN_APPLE).input(Items.GLASS_BOTTLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.GOLDEN_APPLE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonJuice).input(Items.MELON_SLICE,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.MELON_SLICE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleJuice).input(Items.APPLE,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.APPLE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CarrotJuice).input(Items.CARROT,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.CARROT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CarrotSoup).input(Items.CARROT,2).input(Items.BOWL).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.PumpkinBread).input(Items.PUMPKIN).input(Items.WHEAT).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.WHEAT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.SugarBiscuit).input(Items.SUGAR).input(UsefulFoodItems.Biscuit).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleJamBiscuit).input(UsefulFoodItems.Biscuit).input(UsefulFoodItems.AppleJam).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.ChocoBiscuit,2).input(UsefulFoodItems.Biscuit,2).input(UsefulFoodItems.hotchocolatebottle).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CarrotPie).input(Items.EGG).input(Items.CARROT).input(Items.SUGAR).input(Items.WHEAT).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.chocolateicecream).input(UsefulFoodItems.VanillaIceCream).input(UsefulFoodItems.ChocolateCandy).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.ChocolateCandy)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MagicIceCream).input(Items.GLISTERING_MELON_SLICE,2).input(UsefulFoodItems.VanillaIceCream).input(Items.GOLDEN_APPLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.VanillaIceCream)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.SquidSushi).input(UsefulFoodItems.SquidTentacleRaw).input(Items.LILY_PAD).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.LILY_PAD)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CactusJuice).input(Items.CACTUS,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.CACTUS)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Spaghetti).input(Items.BOWL).input(Items.WATER_BUCKET).input(Items.EGG).input(Items.WHEAT).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.WHEAT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleIceCream).input(UsefulFoodItems.VanillaIceCream).input(Items.APPLE).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.APPLE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonIceCream).input(UsefulFoodItems.VanillaIceCream).input(Items.MELON_SLICE,3).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.MELON_SLICE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.ChocolateApple).input(UsefulFoodItems.hotchocolatebottle).input(Items.APPLE).input(Items.STICK).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.APPLE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CaramelBiscuit).input(UsefulFoodItems.caramel).input(UsefulFoodItems.Biscuit).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CheeseSandwich).input(UsefulFoodItems.BreadSlice,2).input(UsefulFoodItems.Cheese).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.Cheese)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CaramelIceCream).input(UsefulFoodItems.VanillaIceCream).input(UsefulFoodItems.caramel).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.caramel)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Cereal).input(Items.WHEAT).input(Items.BOWL).input(Items.SUGAR).input(UsefulFoodItems.MilkBottle).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.ChocolateCereal).input(Items.WHEAT).input(Items.BOWL).input(Items.SUGAR).input(UsefulFoodItems.MilkBottle).input(Items.COCOA_BEANS).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Oatmeal).input(Items.WHEAT_SEEDS,6).input(Items.BOWL).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Jelly).input(Items.SLIME_BALL).input(Items.SUGAR).input(Items.BOWL).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.BOWL)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleJelly).input(UsefulFoodItems.Jelly).input(Items.APPLE).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.Jelly)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonJelly).input(UsefulFoodItems.Jelly).input(Items.MELON_SLICE).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.Jelly)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Donut).input(UsefulFoodItems.MilkBottle).input(Items.WHEAT,2).input(Items.COCOA_BEANS).input(Items.SUGAR).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Oreo).input(UsefulFoodItems.ChocoBiscuit,2).input(Items.SUGAR,2).input(UsefulFoodItems.MilkBottle).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CaramelToast).input(UsefulFoodItems.BreadSlice).input(UsefulFoodItems.caramel).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.caramel)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.SugarToast).input(UsefulFoodItems.BreadSlice).input(Items.SUGAR).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.SugarPancake).input(UsefulFoodItems.PanCake).input(Items.SUGAR).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleJamPanCake).input(UsefulFoodItems.PanCake).input(UsefulFoodItems.AppleJam).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleJamToast).input(UsefulFoodItems.BreadSlice).input(UsefulFoodItems.AppleJam).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.AppleJam)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.AppleJam).input(Items.BOWL).input(Items.SUGAR).input(Items.APPLE).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.APPLE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.CaramelPanCake).input(UsefulFoodItems.caramel).input(UsefulFoodItems.PanCake).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.ChocolatePanCake).input(UsefulFoodItems.ChocolateCandy).input(UsefulFoodItems.PanCake).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonJamPanCake).input(UsefulFoodItems.MelonJam).input(UsefulFoodItems.PanCake).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonJamToast).input(UsefulFoodItems.MelonJam).input(UsefulFoodItems.BreadSlice).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonJamBiscuit).input(UsefulFoodItems.MelonJam).input(UsefulFoodItems.Biscuit).criterion("has_base_item",RecipeProvider.conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.MelonJam).input(Items.MELON_SLICE).input(Items.BOWL).input(Items.SUGAR).criterion("has_base_item",RecipeProvider.conditionsFromItem(Items.SUGAR)).offerTo(exporter);

        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_Jelly).input(UsefulFoodItems.Jelly).input(Items.CHORUS_FRUIT).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Jelly)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_Jelly).input(UsefulFoodItems.Jelly).input(Items.GLOW_BERRIES).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Jelly)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_Jelly).input(UsefulFoodItems.Jelly).input(Items.SWEET_BERRIES).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Jelly)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_Ice_Cream).input(UsefulFoodItems.VanillaIceCream).input(Items.CHORUS_FRUIT).criterion("has_base_item", conditionsFromItem(Items.CHORUS_FRUIT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_Ice_Cream).input(UsefulFoodItems.VanillaIceCream).input(Items.GLOW_BERRIES).criterion("has_base_item", conditionsFromItem(Items.GLOW_BERRIES)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_Ice_Cream).input(UsefulFoodItems.VanillaIceCream).input(Items.SWEET_BERRIES).criterion("has_base_item", conditionsFromItem(Items.SWEET_BERRIES)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_Juice).input(Items.CHORUS_FRUIT,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", conditionsFromItem(Items.CHORUS_FRUIT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_Juice).input(Items.GLOW_BERRIES,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", conditionsFromItem(Items.GLOW_BERRIES)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_Juice).input(Items.SWEET_BERRIES,3).input(Items.GLASS_BOTTLE).criterion("has_base_item", conditionsFromItem(Items.SWEET_BERRIES)).offerTo(exporter);

        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_JamPanCake).input(UsefulFoodItems.Glow_Berries_Jam).input(UsefulFoodItems.PanCake).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_JamToast).input(UsefulFoodItems.Glow_Berries_Jam).input(UsefulFoodItems.BreadSlice).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_JamBiscuit).input(UsefulFoodItems.Glow_Berries_Jam).input(UsefulFoodItems.Biscuit).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Glow_Berries_Jam).input(Items.GLOW_BERRIES).input(Items.BOWL).input(Items.SUGAR).criterion("has_base_item",conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_JamPanCake).input(UsefulFoodItems.Sweet_Berries_Jam).input(UsefulFoodItems.PanCake).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_JamToast).input(UsefulFoodItems.Sweet_Berries_Jam).input(UsefulFoodItems.BreadSlice).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_JamBiscuit).input(UsefulFoodItems.Sweet_Berries_Jam).input(UsefulFoodItems.Biscuit).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Sweet_Berries_Jam).input(Items.SWEET_BERRIES).input(Items.BOWL).input(Items.SUGAR).criterion("has_base_item",conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_JamPanCake).input(UsefulFoodItems.Chorus_Jam).input(UsefulFoodItems.PanCake).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.PanCake)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_JamToast).input(UsefulFoodItems.Chorus_Jam).input(UsefulFoodItems.BreadSlice).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.BreadSlice)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_JamBiscuit).input(UsefulFoodItems.Chorus_Jam).input(UsefulFoodItems.Biscuit).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Biscuit)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Chorus_Jam).input(Items.CHORUS_FRUIT).input(Items.BOWL).input(Items.SUGAR).criterion("has_base_item",conditionsFromItem(Items.SUGAR)).offerTo(exporter);

        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodJamBlocks.Chorus_JAM_JAR).input(UsefulFoodItems.Chorus_Jam,3).input(UsefulFoodJamBlocks.GLASS_JAR).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Chorus_Jam)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodJamBlocks.Sweet_Berries_JAM_JAR).input(UsefulFoodItems.Sweet_Berries_Jam,3).input(UsefulFoodJamBlocks.GLASS_JAR).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Sweet_Berries_Jam)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodJamBlocks.Glow_Berries_JAM_JAR).input(UsefulFoodItems.Glow_Berries_Jam,3).input(UsefulFoodJamBlocks.GLASS_JAR).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Glow_Berries_Jam)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodJamBlocks.Apple_JAM_JAR).input(UsefulFoodItems.AppleJam,3).input(UsefulFoodJamBlocks.GLASS_JAR).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Chorus_Jam)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodJamBlocks.Melon_JAM_JAR).input(UsefulFoodItems.MelonJam,3).input(UsefulFoodJamBlocks.GLASS_JAR).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.Sweet_Berries_Jam)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodJamBlocks.GLASS_JAR).input(Blocks.GLASS).input(ItemTags.WOODEN_SLABS).criterion("has_base_item",conditionsFromItem(Blocks.GLASS)).offerTo(exporter);

        //Reborn 1.5.0
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.Cod_Roe_Sushi).input(Items.COD).input(Items.LILY_PAD).criterion("has_base_item",conditionsFromItem(Items.FISHING_ROD)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.Baked_Sushi).input(ConventionalItemTags.COOKED_FISH_FOODS).input(Items.DRIED_KELP).criterion("has_base_item",conditionsFromTag(ConventionalItemTags.COOKED_FISH_FOODS)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.Salmon_Sushi).input(Items.SALMON).input(Items.DRIED_KELP).criterion("has_base_item",conditionsFromItem(Items.SALMON)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.Fishwich).input(UsefulFoodItems.BreadSlice,2).input(ConventionalItemTags.COOKED_FISH_FOODS).criterion("has_base_item",conditionsFromTag(ConventionalItemTags.COOKED_FISH_FOODS)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.FishSoup).input(Items.CARROT).input(Items.BOWL).input(Items.POTATO).input(ConventionalItemTags.COOKED_FISH_FOODS).criterion("has_base_item",conditionsFromTag(ConventionalItemTags.COOKED_FISH_FOODS)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.ChocolateToast).input(UsefulFoodItems.BreadSlice).input(UsefulFoodItems.ChocolateCandy).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.ChocolateCandy)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.FishnChips).input(UsefulFoodItems.FrenchFries).input(ConventionalItemTags.COOKED_FISH_FOODS).criterion("has_base_item",conditionsFromTag(ConventionalItemTags.COOKED_FISH_FOODS)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.ChocolateCandy).input(Items.COCOA_BEANS).input(ConventionalItemTags.MILK_DRINKS).input(Items.SUGAR).criterion("has_base_item",conditionsFromItem(Items.COCOA_BEANS)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.PanCakeDough).input(Items.SUGAR).input(Items.WHEAT).input(Items.EGG).input(ConventionalItemTags.MILK_DRINKS).criterion("has_base_item",conditionsFromItem(Items.SUGAR)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.Tea).input(Items.GLASS_BOTTLE).input(UsefulFoodItemTagGeneration.ModItemTags.C_Lily_Pads).criterion("has_base_item",conditionsFromItem(Items.GLASS_BOTTLE)).offerTo(exporter);

        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.Trailmix).pattern("#WP").pattern("WMW").pattern(" B ").input('#', Items.BEETROOT_SEEDS).input('W', Items.WHEAT_SEEDS).input('P', Items.PUMPKIN_SEEDS).input('M', Items.MELON_SEEDS).input('B', Items.BOWL).criterion("has_base_item",conditionsFromItem(Items.BEETROOT_SEEDS)).offerTo(exporter);
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.FruitSalad).pattern("#MS").pattern(" B ").input('#', Items.APPLE).input('M', Items.MELON_SLICE).input('S', Items.SWEET_BERRIES).input('B', Items.BOWL).criterion("has_base_item",conditionsFromItem(Items.MELON_SLICE)).offerTo(exporter);
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodItems.MagicFruitSalad).pattern("#GK").pattern(" B ").input('#', Items.GOLDEN_APPLE).input('G', Items.GLISTERING_MELON_SLICE).input('K', Items.GLOW_BERRIES).input('B', Items.BOWL).criterion("has_base_item",conditionsFromItem(Items.GLISTERING_MELON_SLICE)).offerTo(exporter);
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodCakeBlocks.MagicCake).pattern("MMM").pattern("GEG").pattern("WWW").input('M', ConventionalItemTags.MILK_DRINKS).input('G', Items.GOLDEN_APPLE).input('E', Items.ENCHANTED_GOLDEN_APPLE).input('W', Items.WHEAT).criterion("has_base_item",conditionsFromItem(Items.GOLDEN_APPLE)).offerTo(exporter);
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodCakeBlocks.AppleCake).pattern("MMM").pattern("AAA").pattern("WWW").input('M', ConventionalItemTags.MILK_DRINKS).input('A', Items.APPLE).input('W', Items.WHEAT).criterion("has_base_item",conditionsFromItem(Items.APPLE)).offerTo(exporter);
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodCakeBlocks.CaramelCake).pattern("MMM").pattern("CCC").pattern("WWW").input('M', ConventionalItemTags.MILK_DRINKS).input('C', UsefulFoodItems.caramel).input('W', Items.WHEAT).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.caramel)).offerTo(exporter);
        ShapedRecipeJsonBuilder.create(RecipeCategory.FOOD, UsefulFoodCakeBlocks.ChocolateCake).pattern("MMM").pattern("CCC").pattern("WWW").input('M', ConventionalItemTags.MILK_DRINKS).input('C', Items.COCOA_BEANS).input('W', Items.WHEAT).criterion("has_base_item",conditionsFromItem(Items.COCOA_BEANS)).offerTo(exporter);

        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle,8).input(Items.WHEAT, 2).input(Items.SUGAR).input(Items.EGG).input(ConventionalItemTags.MILK_DRINKS).criterion("has_base_item", conditionsFromItem(Items.WHEAT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Vanilla_IceCream,2).input(Items.SNOWBALL).input(Items.SUGAR).input(UsefulFoodItems.Waffle).input(ConventionalItemTags.MILK_DRINKS).criterion("has_base_item", conditionsFromItem(UsefulFoodItems.Waffle)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Chorus_Ice_Cream, 2).input(UsefulFoodItems.VanillaIceCream).input(Items.CHORUS_FRUIT).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(Items.CHORUS_FRUIT)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Glow_Berries_Ice_Cream, 2).input(UsefulFoodItems.VanillaIceCream).input(Items.GLOW_BERRIES).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(Items.GLOW_BERRIES)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Sweet_Berries_Ice_Cream, 2).input(UsefulFoodItems.VanillaIceCream).input(Items.SWEET_BERRIES).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(Items.SWEET_BERRIES)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_chocolate_icecream, 2).input(UsefulFoodItems.VanillaIceCream).input(UsefulFoodItems.ChocolateCandy).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(UsefulFoodItems.ChocolateCandy)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Magic_IceCream, 2).input(Items.GLISTERING_MELON_SLICE,2).input(UsefulFoodItems.VanillaIceCream).input(Items.GOLDEN_APPLE).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(UsefulFoodItems.VanillaIceCream)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Apple_IceCream, 2).input(UsefulFoodItems.VanillaIceCream).input(Items.APPLE).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(Items.APPLE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Melon_IceCream, 2).input(UsefulFoodItems.VanillaIceCream).input(Items.MELON_SLICE,3).input(UsefulFoodItems.Waffle).criterion("has_base_item", conditionsFromItem(Items.MELON_SLICE)).offerTo(exporter);
        ShapelessRecipeJsonBuilder.create(RecipeCategory.FOOD,UsefulFoodItems.Waffle_Caramel_IceCream, 2).input(UsefulFoodItems.VanillaIceCream).input(UsefulFoodItems.caramel).input(UsefulFoodItems.Waffle).criterion("has_base_item",conditionsFromItem(UsefulFoodItems.caramel)).offerTo(exporter);

        //Smelting
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(UsefulFoodItems.SugarCube), RecipeCategory.FOOD,UsefulFoodItems.caramel, 0.45F, 300).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.SugarCube)).offerTo(exporter, "caramel");
        RecipeProvider.offerSmelting(exporter, SEED, RecipeCategory.FOOD,UsefulFoodItems.RoastedSeeds, 0.45F, 300, "food");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(Items.EGG), RecipeCategory.FOOD,UsefulFoodItems.FriedEgg, 0.10F, 200).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.EGG)).offerTo(exporter, "friedegg");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(UsefulFoodItems.Marshmallow), RecipeCategory.FOOD,UsefulFoodItems.CookMarshmallow, 0.60F, 600).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.Marshmallow)).offerTo(exporter, "cookedmarshmallow");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(UsefulFoodItems.SquidTentacleRaw), RecipeCategory.FOOD,UsefulFoodItems.SquidTentacleCooked, 0.35F, 200).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.SquidTentacleRaw)).offerTo(exporter, "cookedsquidtentacle");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(UsefulFoodItems.ChocolateMilkBottle),RecipeCategory.FOOD, UsefulFoodItems.hotchocolatebottle, 0.30F, 200).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.ChocolateMilkBottle)).offerTo(exporter, "hotchocolatemilkbottle");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(UsefulFoodItems.MilkBottle), RecipeCategory.FOOD,UsefulFoodItems.HotMilkBottle, 0.35F, 200).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter, "hotmilkbottle");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(Items.BAKED_POTATO), RecipeCategory.FOOD,UsefulFoodItems.FrenchFries, 0.45F, 300).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BAKED_POTATO)).offerTo(exporter, "frenchfries");
        CookingRecipeJsonBuilder.createSmelting(Ingredient.ofItems(UsefulFoodItems.PanCakeDough), RecipeCategory.FOOD, UsefulFoodItems.PanCake, 0.45F, 300).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCakeDough)).offerTo(exporter, "pancake");

/*        //Campfire
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(UsefulFoodItems.SquidTentacleRaw), RecipeCategory.FOOD,UsefulFoodItems.SquidTentacleCooked, 0.35F, 600).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.SquidTentacleRaw)).offerTo(exporter, "cookedsquidtentacle");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems((ItemConvertible) SEED), RecipeCategory.FOOD, UsefulFoodItems.RoastedSeeds, 0.45F, 600).criterion("has_base_item", RecipeProvider.conditionsFromItem((ItemConvertible) SEED)).offerTo(exporter, "roastedseeds");;
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(Items.EGG), RecipeCategory.FOOD,UsefulFoodItems.FriedEgg, 0.10F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.EGG)).offerTo(exporter, "friedegg");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(UsefulFoodItems.SugarCube), RecipeCategory.FOOD,UsefulFoodItems.caramel, 0.45F, 300).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.SugarCube)).offerTo(exporter, "caramel");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(UsefulFoodItems.Marshmallow), RecipeCategory.FOOD,UsefulFoodItems.CookMarshmallow, 0.60F, 600).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.Marshmallow)).offerTo(exporter, "cookedmarshmallow");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(UsefulFoodItems.ChocolateMilkBottle),RecipeCategory.FOOD, UsefulFoodItems.hotchocolatebottle, 0.30F, 75).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.ChocolateMilkBottle)).offerTo(exporter, "hotchocolatemilkbottle");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(UsefulFoodItems.MilkBottle), RecipeCategory.FOOD,UsefulFoodItems.HotMilkBottle, 0.35F, 200).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter, "hotmilkbottle");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(Items.BAKED_POTATO), RecipeCategory.FOOD,UsefulFoodItems.FrenchFries, 0.45F, 300).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BAKED_POTATO)).offerTo(exporter, "frenchfries");
        CookingRecipeJsonBuilder.createCampfireCooking(Ingredient.ofItems(UsefulFoodItems.PanCakeDough), RecipeCategory.FOOD, UsefulFoodItems.PanCake, 0.45F, 300).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCakeDough)).offerTo(exporter, "pancake");

        //Smoking
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(UsefulFoodItems.SquidTentacleRaw), RecipeCategory.FOOD,UsefulFoodItems.SquidTentacleCooked, 0.35F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.SquidTentacleRaw)).offerTo(exporter);
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems((ItemConvertible) SEED), RecipeCategory.FOOD,UsefulFoodItems.RoastedSeeds, 0.45F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem((ItemConvertible) SEED)).offerTo(exporter, "roastedseeds");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(Items.EGG), RecipeCategory.FOOD,UsefulFoodItems.FriedEgg, 0.10F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.EGG)).offerTo(exporter, "friedegg");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(UsefulFoodItems.SugarCube), RecipeCategory.FOOD,UsefulFoodItems.caramel, 0.45F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.SugarCube)).offerTo(exporter, "caramel");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(UsefulFoodItems.Marshmallow), RecipeCategory.FOOD,UsefulFoodItems.CookMarshmallow, 0.60F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.Marshmallow)).offerTo(exporter, "cookedmarshmallow");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(UsefulFoodItems.ChocolateMilkBottle),RecipeCategory.FOOD, UsefulFoodItems.hotchocolatebottle, 0.30F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.ChocolateMilkBottle)).offerTo(exporter, "hotchocolatemilkbottle");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(UsefulFoodItems.MilkBottle), RecipeCategory.FOOD,UsefulFoodItems.HotMilkBottle, 0.35F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.MilkBottle)).offerTo(exporter, "hotmilkbottle");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(Items.BAKED_POTATO), RecipeCategory.FOOD,UsefulFoodItems.FrenchFries, 0.45F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(Items.BAKED_POTATO)).offerTo(exporter, "frenchfries");
        CookingRecipeJsonBuilder.createSmoking(Ingredient.ofItems(UsefulFoodItems.PanCakeDough), RecipeCategory.FOOD, UsefulFoodItems.PanCake, 0.45F, 100).criterion("has_base_item", RecipeProvider.conditionsFromItem(UsefulFoodItems.PanCakeDough)).offerTo(exporter, "pancake");*/

    }

    public static final List<ItemConvertible> SEED = Util.make(Lists.newArrayList(), list -> {
        list.add(Items.PUMPKIN_SEEDS);
        list.add(Items.MELON_SEEDS);
        list.add(Items.WHEAT_SEEDS);
        list.add(Items.BEETROOT_SEEDS);
    });

}
